apiVersion: v1
kind: Pod
metadata:
  name: resource-limit
spec:
  containers:
  - name: nginx
    image: nginx
    resources:
      requests:
        cpu: 100m
        memory: 68Mi
      limits:
        cpu: 150m
        memory: 100Mi