pipeline{
    agent {
        label 'AGENT-1'
    }
    options {
        timeout(time: 60, unit: 'SECONDS')
        disableConcurrentBuilds()
        retry(1)
    }
    stages {
        stage('Build') {
            steps {
                sh 'echo this is Build'
                sh 'sleep 10'
            }
        }
        stage('Test') {
            steps {
                sh 'echo this is Test'
            }
        }
        stage('Deploy') {
            steps {
                sh 'echo this is Deploy'
                error 'pipeline failed'
            }
        }
    }

    post {
        always{
            echo "This section runs always"
            deleteDir()
        }
    }
}