apiVersion: v1
kind: Pod
metadata:
  name: pod-1
spec:
  containers:
  - name: nginx
    image: nginx:stable-perl
---
apiVersion: v1
kind: Pod
metadata:
  name: pod-2
spec:
  affinity:
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 100
        podAffinityTerm:
          labelSelector:
            matchExpressions:
            - key: security
              operator: In
              values:
              - pod-1
          topologyKey: topology.kubernetes.io/zone
  containers:
  - name: nginx
    image: nginx:stable-perl
---
apiVersion: v1
kind: Pod
metadata:
  name: pod-3
spec:
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - weight: 100
        podAffinityTerm:
          labelSelector:
            matchExpressions:
            - key: security
              operator: In
              values:
              - pod-1
          topologyKey: topology.kubernetes.io/zone
  containers:
  - name: nginx
    image: nginx:stable-perl