apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::273354656091:role/eksctl-expense-nodegroup-expense-NodeInstanceRole-xiFvZ9lF68nr
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    - groups:
      - expense-trainee
      userarn: arn:aws:eks:us-east-1:273354656091:cluster/expense
      username: sai
kind: ConfigMap
metadata:
  creationTimestamp: "2025-04-08T05:17:04Z"
  name: aws-auth
  namespace: kube-system
  uid: 9419b7e7-273f-4c1d-91dd-659cc7d21907